"""Add column file_type in table medias

Revision ID: 3888eba1cd54
Revises: f9e09c86d86e
Create Date: 2024-10-21 21:33:38.238160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3888eba1cd54'
down_revision: Union[str, None] = 'f9e09c86d86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medias', sa.Column('file_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medias', 'file_type')
    # ### end Alembic commands ###
