"""Add ondelete_derective in table likes.

Revision ID: af19eb50a75c
Revises: 3888eba1cd54
Create Date: 2024-10-22 21:24:37.955562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af19eb50a75c'
down_revision: Union[str, None] = '3888eba1cd54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('likes_tweet_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'tweets', ['tweet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_tweet_id_fkey', 'likes', 'tweets', ['tweet_id'], ['id'])
    # ### end Alembic commands ###
