"""Drop table tweet_medias. Add column tweet_id in table medias.

Revision ID: f9e09c86d86e
Revises: cee8e6d4aa39
Create Date: 2024-10-21 20:37:28.243999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e09c86d86e'
down_revision: Union[str, None] = 'cee8e6d4aa39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_medias')
    op.add_column('medias', sa.Column('tweet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'medias', 'tweets', ['tweet_id'], ['id'], ondelete='CASCADE')
    op.drop_column('medias', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medias', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'medias', type_='foreignkey')
    op.drop_column('medias', 'tweet_id')
    op.create_table('tweet_medias',
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tweet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], name='tweet_medias_media_id_fkey'),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], name='tweet_medias_tweet_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'tweet_id', name='tweet_medias_pkey')
    )
    # ### end Alembic commands ###
